### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by nachtschatt3n** [romanblick/collmex-ruby#1]
i created a new rails project with rails new collmextest. 

Just added to the gemfile:
gem 'collmex-ruby', :git => "git://github.com/romanlehnert/collmex-ruby"

And created a collmex-ruby.rb with:
Collmex.setup_login_data( username: "XXXX", password: "XXXX", customer_id: "XXXX" )

then i got with rails c the error:
collmex-ruby.rb:1:in `<top (required)>': uninitialized constant Collmex (NameError)

well rails dont know Collmex ?!

**Comment by nachtschatt3n** [comment]
i use ruby 1.9.2p290 (2011-07-09 revision 32553) [x86_64-darwin11.4.0]

**Comment by romanblick** [comment]
i haven't use this lib in a rails project right now. I'll have a look for it this evening.

**Comment by morgoth** [comment]
@nachtschatt3n looks like you need to specify:

``` ruby
gem "colimex-ruby", require: "colimex"
```

**Comment by romanblick** [comment]
think it works with @morgoth's hint
