### ISSUE TITLE
Obsolete code in released gem

### ISSUE THREAD

**Issue by morgoth** [romanblick/collmex-ruby#2]
Documentation doesn't match code in gem.

Looks like gem was released long time ago.
It throws error at first step:

``` ruby
 Collmex.setup_login_data({})
ArgumentError: wrong number of arguments (1 for 0)
```

`#setup_login_data` looks totaly different than on master branch.

Is this project still maintained?

**Comment by morgoth** [comment]
@romanlehnert I'm integrating Collmex and I'm using your gem.
I already found one bug https://github.com/tiramizoo/collmex-ruby/commit/12e2ef78894b274969de6e3b657edf22c4391e14#L1R224

Would you accept pull request with this one and others?

**Comment by romanblick** [comment]
Hey there. sorry for the long waitingtime. For sure. Would you please send a PR with your changes?

**Comment by morgoth** [comment]
Sure, I will do that tomorrow.

**Comment by romanblick** [comment]
Merged your PR. thanks
